name: Secure CI/CD Pipeline

on:
    push:
        branches: [ secure-cicd-pipeline ]

jobs:
    lint-and-test:
        name: Lint Code and Run Unit Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: action/checkout@v2
            - name: Install dependencies
              run: pip install -r requirements.txt
            - name: Run Linter
              run: flake8 src/
            - name: Run Unit Tests
              run: pytest tests/
    
    build-and-push:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        needs: lint-and-test
        steps:
            - name: Checkout code
              uses: action/checkout@v2
            - name: Build Docker Image
              run: docker build -t security-test-app .
            - name: Login to DockerHub
              run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            - name: Tag and Push Image
              run: |
                docker tag security-test-app:latest "${{ secrets.DOCKERHUB_USERNAME }}"/security-test-app:latest
                docker push "${{ secrets.DOCKERHUB_USERNAME }}"/security-test-app:latest
    
    deploy:
        name: Deploy to Kubernetes
        runs-on: ubuntu-latest
        needs: build-and-push
        steps:
            - name: Checkout code
              uses: action/checkout@v2
            - name: Setup Kubectl
              uses: azure/setup-kubectl@v3
              with:
                version: 'latest'
            - name: Deploy to Kubernetes
              run: |
                kubectl apply -f k8s/deployment.yaml
                kubectl rollout status deployment/security-test-app